version: "2" 
services:
  red:
    image: ceejatec/asterix-centos7
    networks:
      - asterix

  blue:
    image: ceejatec/asterix-centos7
    networks:
      - asterix

  green:
    image: ceejatec/asterix-centos7
    networks:
      - asterix

  cc:
    image: ceejatec/asterix-centos7
    ports:
      - "16001:16001"
      - "19001:19001"
    volumes:
      - "../cluster:/home/couchbase/cluster"
    networks:
      - asterix

  ansible:
    image: ceejatec/asterix-ansible
    volumes:
      - "../ansible:/home/couchbase/ansible"
    networks:
      - asterix

networks:
  asterix:

